import axios from "axios";

interface AIAnalysisPayload {
  code: string;
  language: string;
  output: string;
  expectedOutput: string;
  problem?: {
    id?: string;
    title?: string;
    description?: string;
    difficulty?: string;
  };
  testCases?: Array<{
    input: string;
    expectedOutput: string;
    actualOutput?: string;
    status?: string;
    passed?: boolean;
    errorMessage?: string;
    executionTime?: number;
  }>;
  submission?: {
    id?: string;
    verdict?: string;
    passedTests?: number;
    totalTests?: number;
  };
}

export const generateAIAnalysis = async (
  payload: AIAnalysisPayload
): Promise<string> => {
  try {
    console.log("🤖 [AI] Sending analysis payload:", {
      language: payload.language,
      problem: payload.problem,
      submission: payload.submission,
      codePreview: payload.code.slice(0, 120),
      testCasesCount: payload.testCases?.length ?? 0,
    });

    const response = await axios.post(
      process.env.GENAI_API_URL || "http://localhost:8000/api/ai/feedback",
      payload,
      {
        headers: {
          Authorization: `Bearer ${process.env.GENAI_API_KEY || "local-dev-key"}`,
        },
      }
    );

    return response.data.feedback || "No feedback generated by AI.";
  } catch (error: any) {
    console.error("AI feedback generation failed:", error?.response?.data || error.message);
    return "Unable to generate feedback at the moment.";
  }
};
